import {DEFAULT,plan,readiness,costs,adjust,desired,schedule,totalPeople,validateStored,selectedRecipes} from './engine.js?v=dd0eb357d333';
import {recommend,defaultPreference,reject} from './products.js?v=4508e1d8e812';
const $=s=>document.querySelector(s),main=$('#main'),KEY='sotojitaku_camp_v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const yen=n=>'¥'+Number(n).toLocaleString('ja-JP');
const arrow='<span class="arrow" aria-hidden="true">→</span>';
const primary=(label,action)=>`<button class="primary" ${action}>${label}${arrow}</button>`;
const secondary=(label,action)=>`<button class="secondary" ${action}>${label}${arrow}</button>`;
const image=(id,alt='',cls='',eager=false)=>`<img src="assets/${id}.webp" alt="${esc(alt)}" class="${cls}" ${eager?'fetchpriority="high"':'loading="lazy"'} width="640" height="420">`;
let data,state,hasSaved=false,qIndex=0,mealTab='dinner',gearTab='buy',currentCategory='tent',lastUnlocked=new Set(),saveFailed=false,route='home';
let operator=false;try{operator=new URLSearchParams(location.search).get('test')==='1'||localStorage.getItem('sotojitaku_operator_test')==='1';if(new URLSearchParams(location.search).get('test')==='0')operator=false;localStorage.setItem('sotojitaku_operator_test',operator?'1':'0');}catch{}
try{window['ga-disable-G-GFVSZ8YDQ5']=localStorage.getItem('sotojitaku_analytics_off')==='1';}catch{}
window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){window.dataLayer.push(arguments)};
window.gtag('js',new Date());window.gtag('config','G-GFVSZ8YDQ5',{site_id:'sotojitaku_camp',operator_test:operator?'1':'0',send_page_view:false});
if(operator&&window.parent!==window&&window.PerformanceObserver){new PerformanceObserver(list=>{for(const entry of list.getEntries())if(/google-analytics\.com\/g\/collect/.test(entry.name))window.parent.postMessage({type:'sotojitaku-test-event',event:'ga4_network_request',params:{endpoint:entry.name.split('?')[0],status:entry.responseStatus||'cross_origin',duration:Math.round(entry.duration)}},location.origin);}).observe({type:'resource',buffered:true});}
const analytics=document.createElement('script');analytics.async=true;analytics.src='https://www.googletagmanager.com/gtag/js?id=G-GFVSZ8YDQ5';document.head.append(analytics);
export function track(name,params={}){if(analyticsDisabled())return;if(operator&&window.parent!==window)window.parent.postMessage({type:'sotojitaku-test-event',event:name,params},location.origin);window.gtag('event',name,{site_id:'sotojitaku_camp',operator_test:operator?'1':'0',page_path:location.pathname+location.hash,transport_type:'beacon',...params});}
function fresh(){return {version:1,answers:structuredClone(DEFAULT),gear:{},recipes:[],productPrefs:{},selectedProducts:{},stage:'question',q:0,finished:false};}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function persist(){state.q=qIndex;state.updatedAt=new Date().toISOString();try{localStorage.setItem(KEY,JSON.stringify(state));hasSaved=true;}catch{if(!saveFailed)toast('このブラウザでは保存できません。画面を閉じずに準備を続けてください。');saveFailed=true;}}
function meta(){const a=state.answers,labels={solo:'ひとり',couple:'ふたり',family:'家族',friends:'友人',spring:'春',summer:'夏',autumn:'秋',daytrip:'日帰り',one_night:'1泊2日',car:'車',no_car:'車なし'};return `<div class="plan-meta"><span>${labels[a.party_type]} ${totalPeople(a)}人</span><span>${labels[a.season]}</span><span>${labels[a.stay]}</span><span>${labels[a.transport]}</span></div>`;}
function footer(){return `<footer><div>SOTOJITAKU<br>外へ行く準備を、もっと楽しく。</div><div><a href="#about">このサービスについて</a><a href="#privacy">プライバシー</a><a href="guides/">準備ガイド</a><p>© ${new Date().getFullYear()} SOTOJITAKU</p></div></footer>`;}
function shell(title,eyebrow,body,support='',back='home'){return `<div class="page fade-in"><button class="back" data-go="${back}">← 戻る</button><div class="page-intro"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${support?`<p>${support}</p>`:''}</div>${body}</div>${footer()}`;}
function scene(n,extra='',bonfire=false){const desktop=bonfire&&n===3?'scene-bonfire-hd':n===0?'scene-morning-desktop':n===2?'scene-afternoon-hd':n===3?'scene-evening-hd':`scene-${n}`,portrait=n===0?'morning-portrait':bonfire?'evening-bonfire-portrait':'evening-portrait';return (n===0||n===3?`<picture><source media="(max-width:760px)" srcset="assets/${portrait}.webp">${image(desktop,'森と湖に囲まれたキャンプサイト','scene-image',true)}</picture>`:image(desktop,'森と湖に囲まれたキャンプサイト','scene-image',true))+'<div class="scene-shade"></div>'+extra;}
function sceneNumber(){if(qIndex<3)return 0;if(qIndex<5)return state.answers.stay==='one_night'?1:0;return state.answers.stay==='one_night'?2:0;}
function home(){return `<section class="hero home-hero fade-in">${scene(0)}<div class="hero-copy"><p class="eyebrow">YOUR WEEKEND, YOUR WAY.</p><h1>はじめての<br>キャンプを、<br>あなた仕立てに。</h1><p class="lead">道具も、ごはんも、過ごし方も。<br>やりたい休日から考えよう。</p>${primary('キャンプをつくる','data-start')}<div class="scroll-note">SCROLL TO EXPLORE</div></div></section><section class="section"><div class="section-head"><div><p class="eyebrow">LET’S START HERE</p><h2>どう始める？</h2></div><p class="muted">全部買わなくて大丈夫。<br>あなたに必要なものから、一緒に。</p></div><div class="entry-grid">${[['scene-1','キャンプをつくる','自分に必要なものを、一緒に決める。','data-start'],['cooking','売り場を見る','泊まる・料理・焚き火などから探す。','data-go="store"'],['coffee','やりたいことから探す','BBQ・星空・朝コーヒーなど、過ごしたい時間から。','data-go="experiences"']].map(([img,title,desc,action],i)=>`<button class="entry" ${action}><div class="entry-media">${image(img)}<span class="entry-number">0${i+1}</span></div><h3>${title}${arrow}</h3><p>${desc}</p></button>`).join('')}</div><div class="home-proof"><span>持っている道具を活かす</span><span>買う・借りるを選べる</span><span>予定までつくれる</span></div>${hasSaved?`<div class="resume"><div><strong>前回のキャンプがあります。</strong><p class="muted">途中の回答も、そのまま残っています。</p></div>${secondary('つづきから','data-resume')}</div>`:''}</section><section class="section story">${image('scene-3','灯りがともる、あなたのキャンプ')}<div><p class="eyebrow">MAKE ROOM FOR A GOOD WEEKEND</p><h2>買い物の前に、<br>過ごしたい時間を。</h2><p>焚き火を眺めたり、朝の一杯を楽しんだり。<br>道具は、その時間をかなえるためのもの。</p><p>誰と行くか、何をしたいか。<br>選ぶたびに、自分のキャンプができていきます。</p><button class="back text-link" data-start>わたしのキャンプをつくる →</button><br><a class="back text-link" href="guides/">はじめての準備ガイドを読む →</a></div></section>${footer()}`;}
function experienceTile(o){const on=state.answers.experiences.includes(o.id);return `<button class="experience" data-experience="${o.id}" aria-pressed="${on}">${image(o.id,o.label)}<span class="checkmark" aria-hidden="true">${on?'✓':''}</span><strong>${o.label}</strong></button>`;}
function question(){const q=data.questions.questions[qIndex],a=state.answers;let options='';if(q.type==='single')options=`<div class="options">${q.options.map(o=>`<button class="option" data-answer="${o.id}" aria-pressed="${a[q.id]===o.id}"><span>${o.label}</span><span class="checkmark" aria-hidden="true">${a[q.id]===o.id?'✓':''}</span></button>`).join('')}</div>`;if(q.type==='steppers')options=q.fields.map(f=>`<div class="stepper"><span>${f.label}</span><div class="stepper-control"><button data-step="${f.id}" data-delta="-1" aria-label="${f.label}を1人減らす" ${a[f.id]<=f.min?'disabled':''}>−</button><output aria-live="polite">${a[f.id]}</output><button data-step="${f.id}" data-delta="1" aria-label="${f.label}を1人増やす" ${a[f.id]>=f.max?'disabled':''}>＋</button></div></div>`).join('')+(totalPeople(a)>4?'<p class="note">5人以上の道具選びは個別確認が必要なため、商品推薦の対象外です。計画はつくれます。</p>':'');
 if(q.type==='multi')options=`<div class="experience-grid">${q.options.filter(o=>o.id!=='easy').map(experienceTile).join('')}</div><button class="option easy-option" data-experience="easy" aria-pressed="${a.experiences.includes('easy')}"><span>とにかく簡単に楽しむ</span><span class="checkmark">${a.experiences.includes('easy')?'✓':''}</span></button>`;
 const caption=['まだ何もない。\nここから、休日がはじまる。','誰と行くかで、\n楽しみ方も変わります。','風や光を思い浮かべて。','泊まる場所が、できていく。','荷物も、無理のない量に。','どんな時間を、過ごそう。','全部買わなくて、大丈夫。'][qIndex];
 return `<div class="simulator fade-in"><div class="sim-visual">${scene(sceneNumber())}<div class="scene-label">BUILD YOUR CAMP / ${String(qIndex+1).padStart(2,'0')}</div><div class="sim-caption"><h2>${caption.replace('\n','<br>')}</h2><p>${qIndex>=5?'選んだ時間から、必要な道具と過ごし方を。':'あなたの選択で、キャンプができていきます。'}</p></div></div><section class="question-sheet"><div class="progress"><span>${String(qIndex+1).padStart(2,'0')} / 07</span><div class="progress-line">${Array.from({length:7},(_,i)=>`<i class="${i<=qIndex?'active':''}"></i>`).join('')}</div></div><h1 class="question-title">${q.label}</h1><p class="question-support">${qIndex===5?'やってみたいことを、いくつでも。':qIndex===6?'無理に全部買わなくて大丈夫です。':qIndex===2?'まずは春・夏・秋の、穏やかな日から。':qIndex===4?'車がなくても、身軽なキャンプから。':'あなたらしい休日を、少しずつ。'}</p>${options}${qIndex===5&&a.stay==='daytrip'&&(a.experiences.includes('stargazing')||a.experiences.includes('sleep_comfort'))?'<p class="note">日帰りなら星空・宿泊は次回のお楽しみに。今回は明るいうちに帰る予定をつくります。</p>':''}<div class="question-actions">${primary(qIndex===6?'わたしのプランを見る':'つぎへ','data-next '+(q.type==='multi'&&!a.experiences.length?'disabled':''))}</div><button class="back" data-back-question>← ${qIndex===0?'ホームへ':'ひとつ戻る'}</button><p class="progress-note">選んだ内容は、このブラウザに保存されます。</p></section></div>`;}
function outcomes(){const r=readiness(state,data);return r.unlocked.map(id=>`<span>${esc(data.abilities.abilities.find(x=>x.id===id)?.label||'')}</span>`).join('');}
function provisional(){return shell('あなたのキャンプ、<br>こんな感じになりそうです。','YOUR CAMP, TAKING SHAPE',`${image(state.answers.stay==='one_night'?'scene-2':'scene-0','あなたのキャンプのイメージ','mini-scene')}${meta()}<div class="outcomes">${outcomes()}</div><p class="muted">ここから、持っている道具を引いていきます。</p>${primary('持っている道具を選ぶ','data-go="owned"')}`,'','question');}
const statusLabels={owned:'持っている',buy:'今回そろえる',rent:'今回は借りる',skip:'次回でもOK',undecided:'まだ決めていない'};
function owned(){return shell('もう持っているものは？','USE WHAT YOU HAVE',`<div class="gear-group">${plan(state,data).map(g=>`<div class="gear-row"><button class="owned-button wide" data-owned="${g.id}" aria-pressed="${g.status==='owned'}"><span class="checkmark">${g.status==='owned'?'✓':''}</span><div><h3>${g.label}</h3><p class="muted">${g.quantity>1?`${g.quantity}人分の道具がある場合に選択`:'すでにある道具は購入不要です'}</p></div></button></div>`).join('')}</div>${primary('装備計画へ','data-go="gear"')}`,'持っている道具は、もう買わなくて大丈夫。<br>人数・季節・使い方に合うかだけ確認しましょう。','provisional');}
function costBox(){const c=costs(state,data);return `<div class="cost-summary"><div><p class="muted">今回の道具予算の目安</p><div class="cost-detail"><span>そろえる ${yen(c.buy)}</span><span>借りる ${yen(c.rent)}</span></div></div><div><strong>${yen(c.total)}</strong><p class="muted">${c.limit?'/ 予算 '+yen(c.limit):'快適さを優先'}</p></div></div><p class="muted">購入・レンタル額は計画用の目安です。実売価格・在庫・貸出条件は未確定です。キャンプ場代・交通費・食費・消耗品の追加費用は別途確認してください。</p>${c.over?'<p class="cost-alert">予算を超えています。借りるものや、次回のお楽しみを一緒に見直せます。</p>':''}`;}
function gearRows(filter=null){let p=plan(state,data);if(filter)p=p.filter(filter);return p.map(g=>`<div class="gear-row"><div><h3>${g.label}${g.quantity>1?` <small>×${g.quantity}人分</small>`:''}</h3><p class="muted">${g.core?'まず必要 / 安全・宿泊の基本':g.required?'やりたい時間のために':'あると快適'}${g.status==='owned'?' / 購入予算から除外':g.status==='rent'?' / 貸出先・在庫は要確認':' / 目安 '+yen(g.estimate)}</p></div><select class="gear-status" aria-label="${g.label}の用意の仕方" data-status="${g.id}">${Object.entries(statusLabels).map(([v,t])=>`<option value="${v}" ${g.status===v?'selected':''}>${t}</option>`).join('')}</select></div>`).join('');}
function gear(){return shell('道具が、休日をつくる。','YOUR GEAR PLAN',`${meta()}${costBox()}<div class="outcomes">${outcomes()}</div>${[['まず必要',g=>g.core||g.required],['あると快適',g=>!g.core&&!g.required]].map(([t,f])=>`<section class="gear-group"><h2>${t}</h2>${gearRows(f)}</section>`).join('')}<p class="note">借りるを選んだ道具は、出発前にキャンプ場やレンタル店へ予約・確認を。まだ確保していない場合は「まだ決めていない」に戻してください。</p>${primary('ごはんを考える','data-go="cooking"')}`,'買う・借りる・持っている。<br>全部を買わずに、必要なものから。','owned');}
function cooking(){const easy=state.answers.experiences.includes('easy');const meals=[['dinner',state.answers.stay==='daytrip'?'昼ごはん':'夕ごはん'],...(state.answers.stay==='one_night'?[['breakfast','朝ごはん']]:[]),['snack','おやつ・一杯']];const recipes=data.recipes.recipes.filter(r=>mealTab==='snack'?['snack','drink','rice','meal'].includes(r.meal):r.meal===mealTab).filter(r=>!easy||r.difficulty<=1&&['none','low'].includes(r.cleanup));return shell('今日は、何を食べたい？','GOOD FOOD, GOOD TIME',`${image('cooking','外でつくる、簡単なごはん','mini-scene')}<div class="recipes-tabs" role="tablist">${meals.map(([id,t])=>`<button role="tab" aria-selected="${mealTab===id}" data-meal="${id}">${t}</button>`).join('')}</div>${recipes.map(r=>`<article class="recipe" aria-selected="${state.recipes.includes(r.id)}"><button data-recipe="${r.id}" aria-pressed="${state.recipes.includes(r.id)}"><h3>${r.name}</h3><span class="checkmark">${state.recipes.includes(r.id)?'✓':''}</span></button><p class="muted">${r.id==='no_cook'?'料理をがんばらないのも、立派なキャンプです。':`準備 ${r.prep_time_min}分 / 調理 ${r.cook_time_min}分 / ${r.cleanup==='low'?'片付け軽め':'ゆっくりつくる'}<br>材料：${r.ingredients.join('・')}`}</p></article>`).join('')}<p class="note">夕食・朝食のメインは各1品。料理を選ぶと、鍋・燃料・保冷など必要な道具も計画に加わります。</p>${selectedRecipes(state,data).reduce((s,r)=>s+r.prep_time_min+r.cook_time_min,0)>90?'<p class="warning">料理の準備と調理が合計90分を超えています。ひと品減らすと、のんびりする時間が増えます。</p>':''}${primary('予算を整える','data-go="budget"')}`,'料理をがんばらないのも、立派なキャンプです。','gear');}
function budget(){const r=readiness(state,data);return shell('予算の中で、<br>いちばん大事なものから。','MAKE IT YOURS',`${costBox()}<div class="button-row">${secondary('借りるものを提案してもらう','data-adjust')}${secondary('道具予算を変える','data-go="question" data-question="6"')}</div><section class="gear-group"><h2>買う・借りる・次回にする</h2>${gearRows()}</section>${r.missingCore.length?`<p class="warning">宿泊の基本がまだそろっていません：${r.missingCore.map(g=>g.label).join('・')}。買う・借りる・持っているから選ぶか、日帰りへ変更できます。</p>${secondary('日帰りに変更する','data-daytrip')}`:''}${r.blocked.length?`<p class="note">今回見送る時間：${r.blocked.map(id=>data.abilities.abilities.find(x=>x.id===id)?.label).filter(Boolean).join('・')}。次回の楽しみに残して、できることから予定をつくります。</p>`:''}${plan(state,data).some(g=>g.status==='undecided')?'<p class="warning">まだ決めていない道具があります。用意の仕方を決めると、プランを完成できます。</p>':''}${primary('キャンプを完成させる','data-complete '+(!r.canComplete?'disabled':''))}`,'安全・宿泊の基本と、やりたい時間を大切に。','cooking');}
function complete(){const p=plan(state,data),r=readiness(state,data);if(!r.canComplete)return budget();return `<div class="completion fade-in"><section class="hero">${scene(state.answers.stay==='one_night'?3:0,'',r.unlocked.includes('bonfire'))}<div class="hero-copy"><p class="eyebrow">THIS IS YOUR CAMP.</p><h1>キャンプ、できた。</h1><p class="lead">${r.blocked.length?'今回できることから、<br>あなた仕立ての休日ができました。':'あなたがやりたかったこと、<br>ちゃんとできそうです。'}</p><div class="ability-list">${outcomes()}</div></div></section><section class="completion-summary"><div class="summary-counts">${['owned','buy','rent','skip'].map(s=>`<div>${s==='owned'?'すでに持っている':statusLabels[s]}<strong>${p.filter(g=>g.status===s).length}<small>点</small></strong></div>`).join('')}</div>${meta()}<p class="muted">道具予算の目安 ${yen(costs(state,data).total)}<br>画像はキャンプのイメージです。道具の購入・レンタル予約はこれから確認しましょう。</p>${r.blocked.length?`<p class="note">次回のお楽しみ：${r.blocked.map(id=>data.abilities.abilities.find(x=>x.id===id)?.label).filter(Boolean).join('・')}</p>`:''}<div class="completion-actions">${primary(state.answers.stay==='one_night'?'1泊2日の予定を見る':'日帰りの予定を見る','data-go="schedule"')}${secondary('足りない道具を見る','data-go="missing"')}</div><div class="subnav"><button data-go="gear">装備計画を見直す</button><button data-go="question" data-question="0">回答を見直す</button><button data-export>プランを保存する</button></div></section></div>${footer()}`;}
function schedulePage(){const s=schedule(state,data);return shell('あなたのキャンプの<br>過ごし方','YOUR WEEKEND STORY',`${meta()}<div class="timeline">${s.map((m,i)=>`<article class="moment"><time>${m.time}</time><div class="moment-content"><h2>${m.title}</h2>${(i===2||m.image!=='relax')?image(m.image):''}<p>${m.body}</p>${m.missing.length?`<button class="missing" data-go="gear">あと${m.missing.length}つで、この時間が完成します。<br>${m.missing.join('・')} →</button>`:''}</div></article>`).join('')}</div><p class="note">荒天や強風なら延期・中止も選択肢です。キャンプ場のルール・気温・天気を直前に確認しましょう。時刻は例なので、チェックイン・消灯・チェックアウトは施設に合わせてください。</p>${primary('足りない道具を見る','data-go="missing"')}<div class="subnav"><button data-print>この予定を印刷する</button><button data-export>プランを保存する</button></div>`,'予定を詰めすぎず、何もしない時間も残しています。','complete');}
function productQuantity(id){return plan(state,data).find(g=>g.id===id)?.quantity||1;}
function productBudgetContext(id){const c=costs(state,data),buy=plan(state,data).filter(g=>g.status==='buy'&&data.equipment.categories.some(x=>x.id===g.id));if(c.limit===null||!buy.length)return {quantity:productQuantity(id)};const available=Math.max(0,c.limit-c.rent);const weights={tent:30,sleeping_bag:18,mat:16,chair:10,table:10,cooler:10,led_lantern:8,burner:8,fire_pit:8,hot_sandwich_maker:5};const total=buy.reduce((s,g)=>s+(weights[g.id]||6),0),share=(weights[id]||6)/Math.max(1,total);return {quantity:productQuantity(id),targetBudget:Math.round(available*share)};}
function selectedProduct(id){const code=state.selectedProducts?.[id];if(!code)return null;const p=data.products.products.find(p=>p.itemCode===code&&p.category===id);return p&&!reject(p,id,state.answers,data.equipment)?p:null;}
function productUnits(product,quantity){return Math.max(1,Math.ceil(Math.max(1,quantity||1)/Math.max(1,Number(product?.spec?.persons_per_unit)||1)));}function pickedSummary(){const rows=plan(state,data).filter(g=>g.status==='buy').map(g=>({gear:g,product:selectedProduct(g.id)})).filter(x=>x.product).map(x=>({...x,units:productUnits(x.product,x.gear.quantity)}));return {rows,total:rows.reduce((s,x)=>s+x.product.price*x.units,0)};}
function missing(){const p=plan(state,data),picked=pickedSummary(),buyRecommendable=p.filter(g=>g.status==='buy'&&data.equipment.categories.some(c=>c.id===g.id)),unpicked=buyRecommendable.filter(g=>!selectedProduct(g.id)).length;return shell('そろえる道具','JUST WHAT YOU NEED',`<div class="purchase-progress"><div><p class="eyebrow">YOUR BUY LIST</p><strong>${picked.rows.length} / ${buyRecommendable.length}</strong><span>商品まで決まりました</span></div>${picked.rows.length?`<button class="secondary" data-go="shopping">買うものリストを見る${arrow}</button>`:''}</div><div class="recipes-tabs" role="tablist">${['buy','owned','rent'].map(s=>`<button role="tab" aria-selected="${gearTab===s}" data-gear-tab="${s}">${statusLabels[s]} ${p.filter(g=>g.status===s).length}</button>`).join('')}</div>${p.filter(g=>g.status===gearTab).map(g=>{const selected=selectedProduct(g.id);return `<article class="gear-row"><div><h3>${g.label}${g.quantity>1?' ×'+g.quantity+'人分':''}</h3><p class="muted">${gearTab==='rent'?'貸出先・価格・在庫を事前に確認':gearTab==='owned'?'新しく買わなくて大丈夫':selected?`選択済み：${esc(selected.name)}`:'計画目安 '+yen(g.estimate)}</p></div>${gearTab==='buy'&&data.equipment.categories.some(c=>c.id===g.id)?`<button class="${selected?'picked-button':'secondary'}" data-product="${g.id}">${selected?'✓ 商品を選択済み':'おすすめを決める'}${arrow}</button>`:`<button class="back" data-go="gear">見直す →</button>`}</article>`;}).join('')||'<p class="note">この用意の仕方の道具はありません。</p>'}${gearTab==='buy'&&buyRecommendable.length?`<p class="note">${unpicked? `あと${unpicked}カテゴリの商品を決めると、楽天へ直行できる買い物リストが完成します。`:'買う道具の商品まで決まりました。買うものリストから楽天の商品ページへ順番に進めます。'}</p>`:''}<p class="note">ごみ袋・消火用の水・燃料などの消耗品は、出発前チェックとして別に残します。</p>${picked.rows.length?primary('買うものリストへ','data-go="shopping"'):secondary('過ごし方に戻る','data-go="schedule"')}`,'今回足りないものだけ。<br>道具選びまで、SOTOJITAKUに任せて。','complete');}
const depts=[['stay','泊まる','朝まで眠れる、自分の場所。','sleep_comfort'],['relax','くつろぐ','木陰のひと休みと、外の食卓。','relax'],['cooking','料理する','外で味わう、いつものひと皿。','cooking'],['bonfire','焚き火','火を囲む、静かな時間。','bonfire'],['night','夜を過ごす','灯りをともして、ゆっくりと。','stargazing']];
function store(){return shell('道具から、広がる休日。','THE CAMP STORE',`<div class="store-grid">${depts.map(([id,t,d,img])=>`<button class="store-item" data-dept="${id}">${image(img)}<h2>${t}${arrow}</h2><p>${d}</p></button>`).join('')}</div><p class="note">商品を先に眺めるのではなく、人数・季節・移動・予算から合うものだけを絞ります。キャンプをつくると、さらに正確な提案になります。</p>${primary('自分のキャンプから考える','data-start')}`,'価格を比べる前に、どんな時間を過ごしたい？','home');}
function productPreference(id){return state.productPrefs?.[id]||defaultPreference(id,state.answers);}
function preferenceSelector(c){const cfg=data.productPreferences.categories[c.id];if(!cfg)return '';const selected=productPreference(c.id);return `<section class="preference-box"><div><p class="eyebrow">ONE MORE CHOICE</p><h2>${esc(cfg.question)}</h2><p class="muted">最初の7問で条件は絞れています。ここだけ選ぶと、順位をあなた向けに調整します。</p></div><div class="preference-options">${cfg.options.map(o=>`<button data-product-pref="${o.id}" data-category="${c.id}" aria-pressed="${selected===o.id}"><strong>${esc(o.label)}</strong><span>${esc(o.hint)}</span></button>`).join('')}</div></section>`;}
function productCard(p,c,index){const selected=state.selectedProducts?.[c.id]===p.itemCode,qty=productQuantity(c.id),hero=index===0;return `<article class="product-card ${hero?'hero-pick':''} ${selected?'is-selected':''}"><div class="product-card-head"><p class="badge">${p.badge}</p>${hero?`<span class="match-score">${p.matchScore}<small>/100</small><em>あなた適合</em></span>`:''}</div><img src="${esc(p.image)}" alt="${esc(p.name)}" width="500" height="350" loading="lazy"><div class="why-fit">${p.matchReasons.map(x=>`<span>✓ ${esc(x)}</span>`).join('')}</div><h2>${esc(p.name)}</h2><p class="muted">${qty>1?`1点 ${yen(p.price)} / ${qty}人分なら ${yen(p.totalPrice)}`:`1点 ${yen(p.price)}`} ${p.shipping==='included'?'・送料込み':''}</p><p class="price">${yen(p.totalPrice)}<small class="muted"> ${qty>1?'今回必要な数量の合計':'今回の購入価格'}</small></p>${p.budgetStatus==='over'?'<p class="budget-over">必要条件は満たしますが、この道具の予算配分は超えます。</p>':''}<p class="muted">販売確認 ${esc(p.verifiedAt.slice(0,10))}<br>${esc(p.specSummary||'仕様は販売ページで再確認してください。')}</p><div class="product-actions"><a class="primary" href="${esc(p.affiliateUrl)}" data-affiliate="${esc(p.itemCode)}" data-category="${c.id}" target="_blank" rel="sponsored nofollow noopener">${hero?'これを楽天で買う':'楽天の商品ページへ'}${arrow}</a><button class="${selected?'picked-button':'secondary'}" data-select-product="${esc(p.itemCode)}" data-category="${c.id}">${selected?'✓ 買うものリストに選択済み':'これにする'}${arrow}</button></div></article>`;}
function productsPage(){const c=data.equipment.categories.find(c=>c.id===currentCategory);if(!c)return store();const ctx=productBudgetContext(c.id),pref=productPreference(c.id),recs=recommend(data.products.products,currentCategory,state.answers,data.equipment,data.rules,{...ctx,preference:pref});track('product_view',{category_id:c.id,result_count:recs.length,preference:pref});return shell(`${c.label}、<br>あなたならこれ。`,'CHOSEN FOR YOUR CAMP',`${image(depts.find(d=>d[0]===c.department)?.[3]||'relax','この道具で、楽しめるキャンプの時間','recommendation-scene')}${meta()}<p class="muted">人数・季節・宿泊・移動・やりたいこと・予算を反映して、条件を満たした商品だけから順位をつけています。</p>${preferenceSelector(c)}<div class="category-options">${data.equipment.categories.map(g=>`<button aria-pressed="${g.id===c.id}" data-product="${g.id}">${g.label}</button>`).join('')}</div>${recs.length?`<section class="top-pick"><p class="eyebrow">BEST FOR YOUR CAMP</p><h2>あなたなら、まずこれ。</h2>${productCard(recs[0],c,0)}</section>${recs.length>1?`<section class="alternatives"><div class="section-head"><div><p class="eyebrow">ALTERNATIVES</p><h2>比べるなら、この2つまで。</h2></div><p class="muted">候補を増やしすぎず、違いがあるものだけ。</p></div>${recs.slice(1).map((p,i)=>productCard(p,c,i+1)).join('')}</section>`:''}`:`<section class="empty-products">${image(depts.find(d=>d[0]===c.department)?.[3]||'relax')}<h2>今は、無理に買わない方がいい。</h2><p>あなたの条件を満たし、販売状態まで確認できる商品がありません。検索結果を丸投げせず、このカテゴリは購入候補を表示しません。</p><p>${categoryGuide(c.id)}</p><button class="secondary" data-go="gear">今回は借りる・見直す${arrow}</button></section>`}<p class="muted">商品は本体・販売条件・仕様・適合・楽天の商品ページを確認できたものだけを掲載します。リンクにはアフィリエイト広告を含む場合があります。</p>${secondary('足りない道具へ戻る','data-go="missing"')}`,'検索し直さなくて大丈夫。<br>条件に合うものだけを、少なく。','missing');}
function shopping(){const p=plan(state,data),picked=pickedSummary(),buy=p.filter(g=>g.status==='buy'&&data.equipment.categories.some(c=>c.id===g.id)),unpicked=buy.filter(g=>!selectedProduct(g.id));return shell('買うものまで、<br>決まりました。','YOUR CAMP SHOPPING LIST',`${meta()}<div class="shopping-total"><p>選んだ商品の合計</p><strong>${yen(picked.total)}</strong><span>${picked.rows.length}カテゴリ</span></div>${picked.rows.map(({gear,product,units},i)=>`<article class="shopping-item"><span class="shopping-index">${String(i+1).padStart(2,'0')}</span><img src="${esc(product.image)}" alt="" width="160" height="120" loading="lazy"><div><p class="eyebrow">${esc(gear.label)}${gear.quantity>1?' ×'+gear.quantity:''}</p><h2>${esc(product.name)}</h2><p>${yen(product.price*units)}</p></div><a class="primary" href="${esc(product.affiliateUrl)}" data-affiliate="${esc(product.itemCode)}" data-category="${gear.id}" target="_blank" rel="sponsored nofollow noopener">これを楽天で買う${arrow}</a><button class="back" data-product="${gear.id}">商品を選び直す →</button></article>`).join('')||'<p class="note">まだ商品を選んでいません。</p>'}${unpicked.length?`<section class="unfinished"><h2>あと${unpicked.length}つ、商品を決める</h2>${unpicked.map(g=>`<button class="secondary" data-product="${g.id}">${g.label}のおすすめを見る${arrow}</button>`).join('')}</section>`:'<p class="note">購入予定の主要道具は、商品まで選べています。価格・在庫は楽天の商品ページで最終確認してください。</p>'}${secondary('足りない道具へ戻る','data-go="missing"')}`,'楽天で探し直さず、選んだ商品へそのまま。','missing');}
function categoryGuide(id){return {tent:`${totalPeople(state.answers)}人が眠れる定員と、初心者でも設営できる構造を確認。`,sleeping_bag:'快適使用温度と現地の最低気温を比較。春・秋や標高の高い場所は冷え込みに注意。',mat:'全員分の寝床と断熱性を確認。寝袋とマットは一緒に用意しましょう。',fire_pit:'本体だけでなく、耐熱シート・火ばさみ・耐熱グローブ・消火用の水も。',burner:'器具に対応する燃料を用意し、必ず屋外で使用。',cooler:'人数と食材量に合う容量に、十分な保冷剤を。',hot_sandwich_maker:'直火対応かを確認。電気式は今回の提案対象外です。'}[id]||'人数・重さ・収納サイズと、使いやすさを確認しましょう。';}
function experiences(){return shell('やりたいことから、<br>休日をつくろう。','WHAT WOULD YOU LOVE?',`<div class="experience-grid">${data.questions.questions[5].options.filter(o=>o.id!=='easy').map(experienceTile).join('')}</div><div class="button-row">${primary('選んだ時間でキャンプをつくる','data-experience-start')}</div>`,'大切にしたい時間を、いくつでも。','home');}
function guide(){const rows=[['必要なものは、希望から決まる','泊まるならテント・寝袋・マット・灯り。BBQなら保冷・燃料・網。最初から全部買う必要はありません。'],['予算は、買う・借りる・持っているで整える','まず安全と宿泊の基本を残し、高価で借りやすい道具をレンタルへ。道具予算にはキャンプ場代・食費・交通費を含みません。'],['ファミリーの準備','全員の寝床と灯り、人数に合うテント・食卓・保冷容量を確認。火の周りでは子どもから目を離さず、安定した器具を使いましょう。'],['テント・寝袋・マットを選ぶ','テントの定員と収納サイズ、寝袋の快適使用温度、マットの断熱性。季節だけでなく標高・現地の予報を確認してください。'],['料理・BBQを楽しむ','生肉や魚は十分に保冷して運び、中心まで加熱。肉に触れたトングをそのまま食事に使わず、手洗いと分別も準備。'],['焚き火と灯り','キャンプ場のルールを確認し、テントから火を離す。消火用品を用意し、完全に消火するまでそばを離れない。テント内で火気は使いません。'],['朝ごはんとコーヒー','パンとスープでも、ドリップバッグでも十分。ゆっくり起きて、撤収の時間も残しておきましょう。'],['天気と出発前の確認','荒天・強風なら延期や中止を。施設の営業・設備・受付・消灯・撤収時刻を確認。初回は穏やかな日に設備のあるキャンプ場から。']];return shell('はじめての準備を、<br>気楽に、ていねいに。','YOUR FIRST CAMP',rows.map(([t,d])=>`<details class="accordion"><summary>${t}</summary><p>${d}</p></details>`).join('')+primary('わたしのキャンプをつくる','data-start'),'','home');}
function about(){return shell('外へ行く準備を、<br>もっと楽しく。','ABOUT SOTOJITAKU',`<p>SOTOJITAKU CAMPは、はじめてのキャンプの道具・ごはん・過ごし方を、自分に合わせて組み立てる無料サービスです。</p><h2 class="small-heading">道具より、あなたの休日を。</h2><p>春・夏・秋の日帰り・1泊2日、ソロから4人程度を中心に、やりたいことから必要な道具を考えます。</p><h2 class="small-heading">計画の目安と確認</h2><p>予算は計画用の目安です。購入価格・レンタル先・キャンプ場の予約を確約するものではありません。季節別の商品条件は目安で、現地の最低気温や天候・地形への適合は出発前に確認してください。</p><h2 class="small-heading">商品提案と広告</h2><p>商品は本体・販売条件・仕様・適合を確認できたものだけを掲載します。確認できない場合は表示しません。商品リンクには楽天アフィリエイト広告を含む場合があり、購入により運営者に報酬が発生することがあります。ご利用者の購入価格に追加料金はありません。</p><h2 class="small-heading">画像について</h2><p>キャンプのビジュアルは生成画像によるイメージです。実在するキャンプ場・商品の写真や予約可能な施設を示すものではありません。</p>${secondary('プライバシーを見る','data-go="privacy"')}`,'','home');}
function privacy(){return shell('プライバシーと保存','YOUR DATA',`<h2 class="small-heading">キャンプの保存</h2><p>回答・所有品・装備計画は、この端末のブラウザ内（LocalStorage）に保存されます。氏名や住所を入力する機能はありません。別の端末への同期はありません。</p><h2 class="small-heading">アクセス解析</h2><p>改善のためGoogle Analytics 4を利用し、画面表示・回答の選択・道具の計画・商品リンクのクリックなどの利用状況を計測します。個人を特定する氏名・住所は送信しません。GoogleのCookieや端末等の情報処理については<a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Googleのプライバシーポリシー</a>をご確認ください。</p><h2 class="small-heading">外部の商品ページ</h2><p>楽天等の外部ページへ進んだ後の情報の取り扱い・価格・在庫・購入条件は、各サービスの規定に従います。</p><h2 class="small-heading">保存を削除する</h2><p>このブラウザに保存されたキャンプを削除できます。操作は取り消せません。</p><div class="button-row">${secondary('保存したキャンプを削除','data-delete')}</div><h2 class="small-heading">解析の利用設定</h2><button class="secondary" data-analytics-toggle>${analyticsDisabled()?'解析を許可する':'解析を停止する'}${arrow}</button>`,'','home');}
function analyticsDisabled(){return window['ga-disable-G-GFVSZ8YDQ5']===true;}
function render(animate=false){closeMenu();$('#header').classList.toggle('dark',!['home','question','complete'].includes(route));$('#bottom-nav').hidden=route==='question';$('#bottom-nav').querySelectorAll('a').forEach(a=>{const current=route==='home'?'home':['store','products','experiences'].includes(route)?'store':'camp';if(a.dataset.nav===current)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});const pages={home,question,restart,provisional,owned,gear,cooking,budget,complete,schedule:schedulePage,missing,shopping,store,products:productsPage,experiences,guide,about,privacy};main.innerHTML=(pages[route]||home)();if(!animate)main.querySelectorAll('.fade-in').forEach(e=>e.classList.remove('fade-in'));track('page_view',{page_title:main.querySelector('h1')?.textContent||'SOTOJITAKU CAMP',page_location:location.href});}
function go(next){if(next==='camp'){if(!hasSaved){start();return;}next=state.finished?'complete':state.stage||'question';}if(['provisional','owned','gear','cooking','budget','complete','schedule','missing','shopping'].includes(next)){state.stage=next;persist();}route=next;const hash='#'+next;if(location.hash!==hash)history.pushState({route},'',hash);render(true);window.scrollTo({top:0,left:0,behavior:'instant'});main.focus({preventScroll:true});}
function start(){if(hasSaved){go('restart');return;}state=fresh();qIndex=0;track('simulator_start');persist();go('question');}
function restart(){return shell('キャンプを、新しくつくる？','A NEW WEEKEND',`<p>いま保存している計画を、新しいキャンプに置き換えます。</p><div class="button-row">${primary('新しくつくる','data-new-confirm')}${secondary('つづきから','data-resume')}</div>`,'','home');}
function unlockEvents(){const ids=readiness(state,data).unlocked;for(const id of ids)if(!lastUnlocked.has(id))track('ability_unlock',{ability_id:id});lastUnlocked=new Set(ids);}
function closeMenu(){$('#menu').hidden=true;$('.menu-toggle').setAttribute('aria-expanded','false');}
function changeAnswer(id){const q=data.questions.questions[qIndex];state.answers[q.id]=id;if(q.id==='party_type'){if(id==='solo'){state.answers.adults=1;state.answers.children=0;}else if(id==='family'){state.answers.adults=2;state.answers.children=2;}else{state.answers.adults=2;state.answers.children=0;}}state.finished=false;persist();track('simulator_answer',{question_id:q.id,answer_id:id});render();}
document.addEventListener('click',e=>{const t=e.target.closest('button,a');if(!t)return;if(!data||!state){e.preventDefault();return;}
 if(t.matches('.menu-toggle')){const open=$('#menu').hidden;$('#menu').hidden=!open;t.setAttribute('aria-expanded',String(open));return;}
 if(t.dataset.go){e.preventDefault();if(t.dataset.question!==undefined)qIndex=Number(t.dataset.question);go(t.dataset.go);return;}
 if(t.hasAttribute('data-start')){start();return;}
 if(t.hasAttribute('data-new-confirm')){state=fresh();hasSaved=false;qIndex=0;persist();track('simulator_start');go('question');return;}
 if(t.hasAttribute('data-resume')){qIndex=state.q||0;go(state.finished?'complete':state.stage||'question');return;}
 if(t.dataset.answer){changeAnswer(t.dataset.answer);return;}
 if(t.dataset.experience){const id=t.dataset.experience,arr=state.answers.experiences;state.answers.experiences=arr.includes(id)?arr.filter(x=>x!==id):[...arr,id];state.finished=false;persist();track('simulator_answer',{question_id:'experiences',answer_id:id,selected:state.answers.experiences.includes(id)?1:0});render();return;}
 if(t.dataset.step){const q=data.questions.questions[1],f=q.fields.find(x=>x.id===t.dataset.step);state.answers[f.id]=Math.max(f.min,Math.min(f.max,state.answers[f.id]+Number(t.dataset.delta)));state.finished=false;persist();track('simulator_answer',{question_id:'party_size',adults:state.answers.adults,children:state.answers.children});render();return;}
 if(t.hasAttribute('data-next')){track('question_complete',{question_id:data.questions.questions[qIndex].id});if(qIndex<6){qIndex++;persist();render(true);window.scrollTo({top:0,left:0,behavior:'instant'});}else{if(!state.recipes.length)state.recipes=[state.answers.experiences.includes('bbq')?'bbq':'no_cook'];if(state.answers.stay==='daytrip')state.answers.experiences=state.answers.experiences.filter(x=>!['stargazing','sleep_comfort'].includes(x));if(!state.answers.experiences.length)state.answers.experiences=['relax'];persist();track('gear_plan_generated',{gear_count:plan(state,data).length});unlockEvents();go('provisional');}return;}
 if(t.hasAttribute('data-back-question')){if(qIndex>0){qIndex--;persist();render(true);window.scrollTo({top:0,left:0,behavior:'instant'});}else go('home');return;}
 if(t.dataset.owned){const id=t.dataset.owned;state.gear[id]=state.gear[id]==='owned'?'buy':'owned';state.finished=false;persist();track('gear_owned',{category_id:id,selected:state.gear[id]==='owned'?1:0});unlockEvents();render();return;}
 if(t.dataset.meal){mealTab=t.dataset.meal;render();return;}
 if(t.dataset.recipe){const r=data.recipes.recipes.find(x=>x.id===t.dataset.recipe);if(state.recipes.includes(r.id))state.recipes=state.recipes.filter(x=>x!==r.id);else{if(['dinner','breakfast'].includes(r.meal))state.recipes=state.recipes.filter(id=>data.recipes.recipes.find(x=>x.id===id)?.meal!==r.meal);state.recipes.push(r.id);}
 // Dinner choice is authoritative for BBQ; choosing no-cook removes cooking intent.
 if(r.meal==='dinner'){state.answers.experiences=state.answers.experiences.filter(x=>x!=='bbq'&&(r.id!=='no_cook'||x!=='cooking'));if(state.recipes.includes('bbq'))state.answers.experiences.push('bbq');if(!state.answers.experiences.length)state.answers.experiences=['relax'];}
 state.finished=false;persist();track('recipe_select',{recipe_id:r.id,selected:state.recipes.includes(r.id)?1:0});unlockEvents();render();return;}
 if(t.hasAttribute('data-adjust')){state=adjust(state,data);state.finished=false;persist();track('budget_adjust',{action:'suggest_rent',estimate:costs(state,data).total});unlockEvents();render();toast('安全とやりたい時間を残して、借りるものを提案しました。');return;}
 if(t.hasAttribute('data-daytrip')){state.answers.stay='daytrip';state.answers.experiences=state.answers.experiences.filter(x=>!['sleep_comfort','stargazing'].includes(x));state.recipes=state.recipes.filter(id=>data.recipes.recipes.find(r=>r.id===id)?.meal!=='breakfast');persist();render();return;}
 if(t.hasAttribute('data-complete')){const r=readiness(state,data);if(!r.canComplete)return;state.finished=true;state.stage='complete';persist();track('simulator_complete',{experience_count:r.unlocked.length,estimate:costs(state,data).total});track('schedule_generated',{moment_count:schedule(state,data).length});go('complete');return;}
 if(t.dataset.gearTab){gearTab=t.dataset.gearTab;render();return;}
 if(t.dataset.productPref){state.productPrefs=state.productPrefs||{};state.productPrefs[t.dataset.category]=t.dataset.productPref;persist();track('product_preference',{category_id:t.dataset.category,preference:t.dataset.productPref});render();return;}
 if(t.dataset.selectProduct){state.selectedProducts=state.selectedProducts||{};state.selectedProducts[t.dataset.category]=t.dataset.selectProduct;persist();track('product_select',{category_id:t.dataset.category,product_id:t.dataset.selectProduct});render();toast('買うものリストに追加しました。');return;}
 if(t.dataset.product){currentCategory=t.dataset.product;go('products');return;}
 if(t.dataset.dept){currentCategory=data.equipment.categories.find(c=>c.department===t.dataset.dept)?.id||'tent';go('products');return;}
 if(t.hasAttribute('data-experience-start')){if(!state.answers.experiences.length){toast('やりたい時間をひとつ選んでください。');return;}qIndex=0;track('simulator_start',{source:'experience'});persist();go('question');return;}
 if(t.dataset.affiliate){track('affiliate_click',{affiliate:'rakuten',category_id:t.dataset.category,product_id:t.dataset.affiliate,conversion_source:'camp_missing_gear',link_url:t.href});return;}
 if(t.dataset.externalSearch){track('external_search',{category_id:t.dataset.externalSearch,link_url:t.href});return;}
 if(t.hasAttribute('data-print')){window.print();return;}
 if(t.hasAttribute('data-export')){const p=plan(state,data),s=schedule(state,data);const text=['SOTOJITAKU CAMP','はじめてのキャンプを、あなた仕立てに。',`大人${state.answers.adults}人 / 子ども${state.answers.children}人 / ${state.answers.stay==='one_night'?'1泊2日':'日帰り'}`,`道具予算目安 ${yen(costs(state,data).total)}（実売・予約価格ではありません）`,'','装備計画',...p.map(g=>`${statusLabels[g.status]}：${g.label} ×${g.quantity}`),'','過ごし方',...s.map(m=>`${m.time} ${m.title}\n${m.body}`),'','出発前に天候・施設ルール・予約・在庫を確認。荒天・強風なら延期や中止。','https://stusaurus.github.io/sotojitaku/'].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='SOTOJITAKU-my-camp.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('キャンプの計画を保存しました。');return;}
 if(t.hasAttribute('data-delete')){if(confirm('保存したキャンプを削除しますか？')){try{localStorage.removeItem(KEY);}catch{}state=fresh();hasSaved=false;qIndex=0;go('home');toast('保存したキャンプを削除しました。');}return;}
 if(t.hasAttribute('data-analytics-toggle')){const off=!analyticsDisabled();window['ga-disable-G-GFVSZ8YDQ5']=off;try{localStorage.setItem('sotojitaku_analytics_off',off?'1':'0');}catch{}render();toast(off?'解析を停止しました。':'解析を許可しました。');return;}
 if(t.hash&&t.origin===location.origin){e.preventDefault();go(t.hash.slice(1));}
});
document.addEventListener('change',e=>{if(!data||!state)return;const id=e.target.dataset.status;if(id){state.gear[id]=e.target.value;state.finished=false;persist();track(e.target.value==='owned'?'gear_owned':e.target.value==='rent'?'gear_rent':e.target.value==='buy'?'gear_buy':'gear_status',{category_id:id,status:e.target.value});unlockEvents();const scroll=window.scrollY;render();window.scrollTo({top:scroll,left:0,behavior:'instant'});}});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});
window.addEventListener('popstate',()=>{route=location.hash.slice(1)||'home';if(route==='camp')route=hasSaved?(state.finished?'complete':state.stage||'question'):'home';render();});
async function init(){try{try{window['ga-disable-G-GFVSZ8YDQ5']=localStorage.getItem('sotojitaku_analytics_off')==='1';}catch{}const entries=await Promise.all(['questions','equipment','abilities','recipes','recommendation-rules','product-preferences'].map(async id=>{const r=await fetch(`data/${id}.json`);if(!r.ok)throw Error(id);return [id==='recommendation-rules'?'rules':id==='product-preferences'?'productPreferences':id,await r.json()];}));data=Object.fromEntries(entries);try{const r=await fetch('data/products.json',{cache:'no-cache'});data.products=r.ok?await r.json():{products:[]};}catch{data.products={products:[]};}if(!Array.isArray(data.products.products))data.products={products:[]};try{const saved=validateStored(JSON.parse(localStorage.getItem(KEY)),data);if(saved){state=saved;hasSaved=true;qIndex=Math.max(0,Math.min(6,Number(state.q)||0));}}catch{}state=state||fresh();if(operator&&window.parent!==window)window.parent.postMessage({type:'sotojitaku-test-event',event:'storage_restore',params:{restored:hasSaved,stage:state.stage,finished:state.finished,owned:Object.keys(state.gear).filter(k=>state.gear[k]==='owned').length}},location.origin);lastUnlocked=new Set(readiness(state,data).unlocked);route=location.hash.slice(1)||'home';if(route==='camp')route=hasSaved?(state.finished?'complete':state.stage||'question'):'home';render();}catch(e){main.innerHTML=shell('準備データを読み込めませんでした。','PLEASE TRY AGAIN','<p>通信を確認して、もう一度開いてください。保存済みのキャンプは削除していません。</p><button class="primary" data-retry>もう一度読み込む →</button>');document.querySelector('[data-retry]').onclick=()=>location.reload();}}
await init();
