import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import {spawnSync} from "node:child_process";

const repo=path.resolve(import.meta.dirname,"..");
function auditFixture(change){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),"soto-fishing-coverage-"));
  try{
    fs.cpSync(path.join(repo,"fishing"),path.join(dir,"fishing"),{recursive:true});
    fs.writeFileSync(path.join(dir,"package.json"),JSON.stringify({type:"module"}));
    const file=path.join(dir,"fishing/data/audited-products.json");
    const catalog=JSON.parse(fs.readFileSync(file,"utf8"));
    change?.(catalog);
    fs.writeFileSync(file,JSON.stringify(catalog));
    const output=path.join(dir,"report.json");
    const result=spawnSync(process.execPath,[path.join(dir,"fishing/scripts/check_scenarios.mjs"),output],{encoding:"utf8"});
    assert.ok(fs.existsSync(output),result.stderr);
    return {result,report:JSON.parse(fs.readFileSync(output,"utf8"))};
  }finally{
    // This exact directory is generated by this test, never a user workspace.
    fs.rmSync(dir,{recursive:true,force:true});
  }
}
test("acknowledged gaps remain visible without claiming complete coverage",()=>{
  const {result,report}=auditFixture();
  assert.equal(result.status,0,result.stderr);
  assert.equal(report.scenarioCount,2916);
  assert.equal(report.safetyAndUnexpectedCoveragePassed,true);
  assert.equal(report.coverageComplete,false);
  assert.ok(report.knownGapOccurrences>0);
  assert.equal(report.knownGaps.reduce((n,g)=>n+g.scenarioOccurrences,0),report.knownGapOccurrences);
  assert.equal(report.knownGaps.length,4);
  assert.ok(report.knownGapExamples.length<=12);
});
test("a stopped seed alone does not imply a gap after an eligible replacement exists",()=>{
  const {result,report}=auditFixture(catalog=>{
    // Synthetic product fixture only. Never published or used as product evidence.
    const rod=catalog.products.find(p=>p.categoryId==="rod_reel"&&p.methodIds.includes("sabiki"));
    assert.ok(rod);
    const second=catalog.products.find(p=>p.categoryId==="rod_reel"&&p.methodIds.includes("choi_nage"));
    assert.ok(second);
    for(const p of [rod,second])p.budgetTiers=["low","balanced","long_term"];
  });
  assert.equal(result.status,0,result.stderr);
  assert.equal(report.knownGapOccurrences,0);
  assert.equal(report.coverageComplete,true);
  assert.equal(report.knownGaps.length,0);
});
test("a new required-product gap fails and still produces its report",()=>{
  const {result,report}=auditFixture(catalog=>{
    catalog.products=catalog.products.filter(p=>!p.coverCategoryIds?.includes("life_jacket_adult"));
  });
  assert.equal(result.status,1);
  assert.equal(report.safetyAndUnexpectedCoveragePassed,false);
  assert.equal(report.coverageComplete,false);
  assert.ok(report.unexpectedFailureCount>0);
  assert.ok(report.unexpectedFailureExamples.some(f=>f.unresolved?.includes("life_jacket_adult")));
});
